### ISSUE TITLE
Issue on page /Start_Here/help_sessions.html

### ISSUE THREAD

**Issue by amedlyn** [Purdue-ENGR-13300/fall-2024#18]
When I try to join the meeting, it says "waiting for host to start the meeting."

**Comment by jhcole** [comment]
@amedlyn What time did you try to join?

**Comment by jhcole** [comment]
We may have been between office hours when you tried to join. You can find the full schedule [here](https://purdue-engr-13300.github.io/fall-2024/Start_Here/help_sessions.html). Please let us know if you have problems in the future.
