### ISSUE TITLE
Issue on page /Part_1_Excel/M1/0_overview.html

### ISSUE THREAD

**Issue by BHS1906** [Purdue-ENGR-13300/fall-2024#2]
- [ Missing CO 1.1 or miss numbered ] 
<img width="872" alt="Screenshot 2024-06-18 at 11 34 03 PM" src="https://github.com/Purdue-ENGR-13300/fall-2024/assets/45901196/f40791a9-e036-4dc4-a4c8-4450922fa758">

**Comment by jhcole** [comment]
You can find all the course outcomes here: https://purdue-engr-13300.github.io/fall-2024/intro.html

CO 1.1 is: Visually represent data and derive meaningful information from data.

I don't think this applies to Ex 1.
