### ISSUE TITLE
Issue on page /Part_3_Python/M2/tasks/team_3/a/instructions.html

### ISSUE THREAD

**Issue by DavidVasilev1** [Purdue-ENGR-13300/fall-2024#21]
Calculation error in test case 1:

`The amount of heat output by the heater is 3004770010.3 J`

The value for the heat output is not correct. The correct heat value should be 417329.2 W * 2 hours = 834658.3 J

**Comment by sdustker** [comment]
make sure the time is in seconds. We have given you time in hours. 417329.2 W * 2 hours * 3600 = 3004770010.3 J
