### ISSUE TITLE
Issue on the autograder

### ISSUE THREAD

**Issue by landonj526** [Purdue-ENGR-13300/fall-2024#28]
The auto grader has been the worst part of this class by far. I like coding, but trouble shooting in the auto grader is terrible. Our work should be graded by real people with the auto grader just as a guide to error problems instead of actually contributing to the grade. If you want to keep the auto grader, make sure to specify exactly the functions and techniques you want us to use if we had not learned it in class.

**Comment by jhcole** [comment]
Your feedback has been noted.
