### ISSUE TITLE
Issue on page /Part_3_Python/M4/tasks/pre_0/a/instructions.html

### ISSUE THREAD

**Issue by mprez23** [Purdue-ENGR-13300/fall-2024#30]
I keep getting this issue, but my code works on vs code and all looks well but still have this issue 
<img width="1440" alt="Screenshot 2024-09-23 at 4 30 36 PM" src="https://github.com/user-attachments/assets/a87f6016-5e58-411c-ba2e-b8d2de1da111">
<img width="1440" alt="Screenshot 2024-09-23 at 4 30 36 PM" src="https://github.com/user-attachments/assets/38bf0acf-625e-43d1-83ef-6a4c33b345d2">

**Comment by jhcole** [comment]
This question belongs on Campuswire.  Also, remember not to post code publicly.
