### ISSUE TITLE
Issue on page /Part_4_Team_Project/M2/1.1_materials.html

### ISSUE THREAD

**Issue by jackkarson** [Purdue-ENGR-13300/fall-2024#37]
![image](https://github.com/user-attachments/assets/468a6685-2b89-4917-b144-ee70daf2c228)

Why is the generated XOR binary use "Decimal" to get characters instead of going through ASCII like the previous conversions?

**Comment by jhcole** [comment]
It should have said "ASCII Code" like the others.
