### ISSUE TITLE
Issue on page /Start_Here/course_schedule.html

### ISSUE THREAD

**Issue by heesookiim** [Purdue-ENGR-13300/fall-2024#38]
Doesn't specify checkpoints deadline correctly.

**Comment by jhcole** [comment]
We intentionally left the checkpoint 2 due date in the calendar as 10/10 instead of 10/15 and reminded students in class that they should have it done by the 10th even though they won't present until the 15th.  Next semester, we plan to keep it on Thursday and move the CQ to Tuesday instead.
